version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python main.py'
        ports:
            - 80:5001
        volumes: 
            - .:/app
